// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

import BlockFormController from "./block_form_controller"
application.register("block-form", BlockFormController)

import CategorySelectorController from "./category_selector_controller"
application.register("category-selector", CategorySelectorController)

import FormValidationController from "./form_validation_controller"
application.register("form-validation", FormValidationController)

import GoogleMapController from "./google_map_controller"
application.register("google-map", GoogleMapController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MenuItemsController from "./menu_items_controller"
application.register("menu-items", MenuItemsController)

import MobilemenuController from "./mobilemenu_controller"
application.register("mobilemenu", MobilemenuController)

import ScreenshotController from "./screenshot_controller"
application.register("screenshot", ScreenshotController)

import PlayguideController from "./playguide_controller"
application.register("playguide", PlayguideController)

import SettingsFormController from "./settings_form_controller"
application.register("settings-form", SettingsFormController)

import SlideshowController from "./slideshow_controller"
application.register("slideshow", SlideshowController)
