default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: star_trader_development
  cable:
    <<: *default
    database: star_trader_development
    schema_search_path: "cable,public"
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: star_trader_test
  cable:
    <<: *default
    database: star_trader_test
    schema_search_path: "cable,public"
    migrations_paths: db/cable_migrate

production:
  primary:
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  cable:
    url: <%= ENV["DATABASE_URL"] %>
    schema_search_path: "cable,public"
    migrations_paths: db/cable_migrate
